# Generated by Django 4.2.9 on 2024-01-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mymodel_delete_yourmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
